---
title: "Assignment 1"
author: "Allison Bailey"
date: "3/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Management of Fall Quarter 2020 UCSB - Bren Courses
This database contains all readings, syllabi, assignments and subsequent files for those assignments for each course taken Fall Quarter 2020. 

### Typographic Conventions

* ```literal```: fixed parts of file or folder names
* *variable*: variable parts of file or folder names
  + *yyyy-mm-dd*: a calendar date in ISO 8601 format

### Structure and Naming Conventions
* ```README.md```: this file
* ```fall_2020/```: This folder contains coursework for Fall 2020 at Bren.
  + *esm_xxx*/: Files related to a specific course within Bren
    + ```readings/```: Reading required for the course
      + *date_author_abr-title.pdf*: readable pdf file 
    + ```labs/```: Weekly labs for the course
      + *lab-1*/: Specific lab number.
        + ```working_document/```: Working lab document
          + *date_lab-number.docx*: Readable microsoft word document
        + ```data/```: Data for a specific lab
          + *date_lab-number_description.csv*: data calculated from lab in csv format
          +  *date_lab-number_description.rmd*: R Markdown document associated with lab
          +  *date_lab-number_description.rproj*: R Project associated with lab
    + ```assignments/```: Assignments required for each course
      + *assignment_1*/: Specific assignment number.
        + ```sources/```:
          +  *date_author-abr-title.pdf*: readable pdf file
        + ```data/```: Data for a specific assignment
        + ```documents/```: Documents needed for the assignment
        + ```working_document/```: Working assignment document
         
        
### Example

Below is an example of ESM 214:Bio Waste Water Treatment file directory.

* ```fall_2020/```
  + *esm_214*/
    + ```readings/```
      +  *2017-01-19_liang-nat-microbiology.pdf*
    + ```labs/```
      + *lab-1*/
        +  *2020-10-15_lab-1.docx*
        + ```data/```
          +  *2020-10-15_lab-1_bacteria-counts.csv*
          +  *2020-10-15_lab-1_bacteria-counts.rmd*
          +  *2020-10-15_lab-1_bacteria-counts.rproj*
    + ```assignments/```
      + *assignment-1*/
        + ```data/```
        + ```documents/```
          +  *2020-10-20_assignment-1_instructions.docx*
        + ```sources/```
          +  *2017-01-19_liang-nat-microbiology.pdf*
        + ```working_document/```
          +  *2020-10-20_assignment-1.docx*
